
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PacmanREST.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Fence
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Fence()
    {

        this.FencePoints = new HashSet<FencePoint>();

    }


    public int ID { get; set; }

    public int Pacman_carer_dbID { get; set; }

    public int Pacman_patient_dbID { get; set; }



    public virtual Pacman_carer_db Carer { get; set; }

    public virtual Pacman_patient_db Patient { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FencePoint> FencePoints { get; set; }

}

}
