//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacmanREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fence
    {
        public int ID { get; set; }
        public int Pacman_carer_dbID { get; set; }
        public int Pacman_patient_dbID { get; set; }
    }
}
