//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacmanREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacman_location_db
    {
        public int? ID { get; set; }
        public decimal coordinates_x { get; set; }
        public decimal coordinates_y { get; set; }
        public Nullable<int> id_patient { get; set; }
        public Nullable<int> id_carer { get; set; }
    }
}
