//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacmanREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacman_fence_db
    {
        public int? ID { get; set; }
        public int id_location { get; set; }
        public decimal radius { get; set; }
        public string description { get; set; }
        public int id_carer { get; set; }
        public int id_patient { get; set; }
    }
}
