
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PacmanREST.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Pacman_carer_db
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pacman_carer_db()
    {

        this.Fences = new HashSet<Fence>();

    }


    public int ID { get; set; }

    public string name { get; set; }

    public int phone { get; set; }

    public string email { get; set; }

    public string address { get; set; }

    public string device_id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Fence> Fences { get; set; }

}

}
